This is C:\Program Files\MiKTeX 2.8\miktex\bin\makeindex.exe, version 2.14 [02-Oct-2002] (kpathsea + Thai support).
Scanning style file D:/tuhh/ss10/master thesis_coremedia/projects/Tag-Cloud-Summarizer/report/thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (4 entries accepted, 0 rejected).
Sorting entries....done (10 comparisons).
Generating output file thesis.acr....done (8 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
