This is makeindex, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file D:/tuhh/ss10/thesis/projects/Tag-Cloud-Summarizer/report/thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (106 entries accepted, 0 rejected).
Sorting entries....done (821 comparisons).
Generating output file thesis.acr....done (51 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
